FROM python:3.12-slim-bookworm AS base

WORKDIR /usr/src/app

COPY /src/recommendation/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY /src/recommendation .

ENTRYPOINT ["python", "recommendation_server.py"]
